### PR TITLE
Add connectable squeekboard layouts plug

### PR DESCRIPTION
**Pull request by jrmcpeek**
In the [current documentation](https://mir-server.io/docs/ubuntu-frame-osk-documentation), the steps to add custom layouts asks the user to shell into the snap context and make modifications in `$SNAP_USER_DATA/.local/share`.

In our environment, we'd like to be able to use the keyboard without emoji or terminal views being present, which was [recently asked about](https://discourse.ubuntu.com/t/ubuntu-frame-osk-documentation/27568/20) on discourse by another user.

These changes don't appear to be exposed by the ubuntu-frame-osk snap, nor does it appear configurable by squeekboard upstream - the emoji and terminal views are hardcoded into `popover.ui`.

Injecting custom layouts that exclude the preferences button (or other changes) does not appear possible using existing interfaces, so I'm proposing the addition of a `keyboard-layouts` plug.

This change:
* Adds the new plug, targeting `$SNAP_COMMON/squeekboard/keyboards`
* Adds an environment variable `SQUEEKBOARD_KEYBOARDSDIR` to point to `$SNAP_COMMON/squeekboard/keyboards`
  * As far as I can tell, this is necessary to enable content interface sharing, as it appears a [previous discussion](https://forum.snapcraft.io/t/content-interface-and-snap-user-data/6451/7) on the ability to map content interfaces to `$SNAP_USER_DATA` stalled out.
 
To use this plug:
* A producer snap with a `keyboard-layouts` slot:
  * Shares read-only yaml files under a `keyboards` folder
  * Follows the [upstream folder layout](https://gitlab.gnome.org/World/Phosh/squeekboard/-/tree/v1.17.1/data/keyboards) within this shared folder
* A user establishes a connection on this interface
  * This can be done manually, or after this change, programmatically.

### CODE REVIEW

**Comment by Saviq** [comment]
Thanks @jrmcpeek!

We're currently busy with a number of things, but we'll get to this as soon as we can.

One question, would prepending to `$XDG_DATA_DIRS` not work? That's where squeekboard _should_ be looking, when there isn't anything in `$XDG_DATA_HOME`.

**Comment by jrmcpeek** [comment]
> One question, would prepending to `$XDG_DATA_DIRS` not work?

I can check and report back.

Looking at the way it's implemented in squeekboard:

* It first looks at a [custom environment variable](https://gitlab.gnome.org/World/Phosh/squeekboard/-/blob/master/src/data/loading.rs#L223) (`SQUEEKBOARD_KEYBOARDSDIR`, if defined).
* If that fails, [it checks](https://gitlab.gnome.org/World/Phosh/squeekboard/-/blob/master/src/xdg.rs#L57) `$XDG_DATA_HOME`

**Comment by Saviq** [comment]
> Without `$XDG_DATA_HOME` defined, it inevitably falls back to `$SNAP_USER_DATA/.local/share`.

Thanks for checking! I was confused for a moment how did it find the default layouts, but those are baked into the binary of course.

**Comment by mattkae** [comment]
@Saviq This is working on my end by the way! To reproduce:

1. Build the `ubuntu-frame-osk` snap locally (or get it from the PR if you like)
2. Create your snap and add the following to the `snapcraft.yml`

```yaml
name: provider
version: '0.1'
summary: Single-line elevator pitch for your amazing snap
description: Testing
base: core22

grade: devel
confinement: devmode

parts:
  my-part:
    plugin: dump
    source: .

slots:
  shared-files:
    content: shared-files
    interface: content
    read:
    - $SNAP/data
```

3. Create a top-level folder for the snap called `data`. 
4. Inside of `data`, clone the contents of [this project](https://github.com/mikeshenson/Phosh-Squeekboard-Keyboard/tree/main) for testing. Rename `Phosh-Squeekboard-Keyboard` to `keyboards`. (Your directory will now be `data/keyboards/<YAML_FILES>`)
5. Build the snap and install it
6. Once installed, make the connection: `sudo snap connect ubuntu-frame-osk:keyboard-layouts provider:shared-files`
6. Confirm that the files are present for ubuntu-frame-osk (if you want to):
```sh
snap run --shell ubuntu-frame-osk
ls $SNAP_DATA/.share/squeekboard/keyboards/
```
7. Run `ubuntu-frame-osk` and see the new keyboard

**Comment by Saviq** [comment]
Thanks all, in general I'm for this, but I'm not entirely happy with this taking over the whole of `XDG_DATA_HOME`.

Since there is the `SQUEEKBOARD_KEYBOARDSDIR` variable, and the only currently supported layout format is the squeekboard one (we purposely called the snap `-osk`, not `-squeekboard`, so that we can make a different choice in the future), should we use that environment var, and call the interface `squeekboard-layouts`?

**Comment by jrmcpeek** [comment]
@Saviq

> we purposely called the snap -osk, not -squeekboard, so that we can make a different choice in the future

This was the reason I had proposed `keyboard-layouts` and not `squeekboard-layouts` originally, to be a bit more generic.

If you completely change the keyboard app, and the new app doesn't use squeekboard layout configs, for sure this would then break.

But, so too will any provider that simply tries to provide custom layouts over a `squeekboard-layouts` interface - it will stop getting consumed at that point in the future.

It seems like, no matter which you choose, _if_ ubuntu-frame-osk changes to a completely different underlying keyboard, _then_ providers will need to do work to keep working anyway.

> should we use that environment var, and call the interface squeekboard-layouts?

With that said, I'm happy to make an update to use the `SQUEEKBOARD_KEYBOARDSDIR` approach instead, as it doesn't much make a difference from the provider perspective.

Would you prefer a separate pull request entirely, and decide which to go with?

And do you want to see the connection name change from `keyboard-layouts` to `squeekboard-layouts`?

**Comment by AlanGriffiths** [comment]
> > And do you want to see the connection name change from `keyboard-layouts` to `squeekboard-layouts`?
> 
> That would be my vote, yes.

Another motivation for this change is that the name `keyboard-layouts` is too generic - nothing ties it to Frame OSK or even an OSK in general. With `squeekboard-layouts` the implication of using the interface with another squeekboard snap isn't actively misleading.

**Comment by jrmcpeek** [comment]
I made updates based on the feedback so far.

The interface is now named `squeekboard-layouts` instead of `keyboard-layouts`.

`XDG_DATA_HOME` is no longer defined.

`SQUEEKBOARD_KEYBOARDSDIR` is now defined with a mount point under `$SNAP_COMMON` (based on https://snapcraft.io/docs/environment-variables#heading--snap-common, this appears a more appropriate place for this).

Because the environment variable includes `KEYBOARDSDIR`, the paths were updated to be _inclusive_ of `keyboards`.

Functionality is otherwise unchanged. Since the layout files are only loaded when squeekboard starts, a restart is required after the interface connection is made.

I didn't try to automate this (nor am I sure it would necessarily be desirable), but it looks like this can be accomplished with https://snapcraft.io/docs/interface-hooks.

**Review by AlanGriffiths — APPROVED** [review]
This works as advertised and doesn't break things.

My one concern is whether the content interface could need versioning in the event of changes to the expected YAML. It doesn't seem like a big risk, but maybe someone knows better?

**Comment by jrmcpeek** [comment]
@AlanGriffiths

> It doesn't seem like a big risk, but maybe someone knows better?

While the past remains a poor predictor of the future, the YAML files look to have been authored around 4 years ago. There was one structural change shortly after the first inclusion, but otherwise it looks like just "feed-forward" capabilities of only _extending_ the format through new sections over time - but even those were within the first month of the addition of these config files.

I would guess that your assessment of it being a not a big risk is likely correct.

**Comment by Saviq** [comment]
Thanks again @jrmcpeek!

**Pull request merged**
