### PR TITLE
[Merged by Bors] - Use squeekboard v1.17.1

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Pick up fix for https://bugs.debian.org/1007115

### CODE REVIEW

**Comment by wmww** [comment]
Ok, nice that they got a release out to fix that. I'll need to test it (later). Not urgent because we already have a patch to fix that bug (that patch failing to apply is probably why the build is broke).

**Comment by wmww** [comment]
Looking at the commits [here] this release seems to include two of our backport patches, which can now be dropped. It also includes my fix for a minor issue to do with the terminal layout not always being chosen correctly, which we didn't bother to patch. I've tested and everything is working fine with those patches dropped.

**Review by AlanGriffiths — COMMENTED** [review]
LGTM

bors merge

**Review by Saviq — APPROVED** [review]
bors merge r=wmww

**Pull request closed without merging**
