### PR TITLE
[Merged by Bors] - Upgrade to Squeekboard 1.17.0

### LINKED ISSUE #37: FTBFS with unchanged rebuild
Attempting a rebuild today (following a "contains outdated Ubuntu packages" notification) gives the following error:

```
Program msgfmt found: NO

../src/data/meson.build:15:5: ERROR: Program 'msgfmt' not found or not executable
```

As well as the immediate problem, this means that we cannot reliably control the build content.

### PR DESCRIPTION
**Pull request by wmww**
Fixes #37 and brings in a slightly modernized look for Squeekboard.

Patches:
- The null d-bus handler check I wrote was merged, so that patch is dropped
- A patch is included to work around some Rust dependency issues (See #37)
- A patch is included to fix a regression that causes the keyboard to be too big on hidpi displays (see https://gitlab.gnome.org/World/Phosh/squeekboard/-/issues/327)

Both of the new patches are from current master, so will be dropped next Squeekboard release.

### CODE REVIEW

**Comment by wmww** [comment]
I've built the snap locally and tested it and everything seems to work fine.

**Review by AlanGriffiths — APPROVED** [review]
Works, but I'm still concerned that we pull "random stuff from the internet".

bors merge

**Comment by wmww** [comment]
> Works, but I'm still concerned that we pull "random stuff from the internet".

Isn't that what building a snap fundamentally is? You pull from source repos. You pull from the Ubuntu Archives. You pull from language-specific dependency sources (crates.io for Rust), and then you compile it all.

**Comment by AlanGriffiths** [comment]
> What specific source do you take issue with?

It isn't _necessarily_ the source. It is that we pull stuff that isn't compatible with what we pulled last time.

E.g. the Ubuntu Archive is guaranteed to be ABI compatible. We relax that for our own PPAs, but we still have control over when they change.

We pull a specific version of squeekboard - so updates to that source repository shouldn't affect us.

We _don't_ pull specific versions from crates.io (for example), and that's what means we can't, for example, do a rebuild to pick up security updates from the Ubuntu archive.

**Comment by wmww** [comment]
We *do* pull specific versions from crates.io (this is specified in Squeekboard's [Cargo.lock](https://gitlab.gnome.org/World/Phosh/squeekboard/-/blob/master/Cargo.lock) file). What happened wasn't an update. It was an old version that got "yanked". I don't fully understand what that means or why it caused a problem (from my reading of docs it should have), but in any case it was a special case.

**Comment by AlanGriffiths** [comment]
Hmm. The error message isn't what I'd expect in that case. But OK

**Comment by wmww** [comment]
Honestly, I don't know precisely what happened. I'm fairly sure the crate yanking was involved, but perhaps there was some other issue at the same time? If this kind of thing happens with regularity it will definitely be worthwhile to get to the bottom of why and address the underlying issue, but I think there's a decent chance whatever it was was one-off.

**Pull request closed without merging**
